name: PublishVLNuget
description: Publishes a VL nuget

inputs:
  nuspec:
    description: The path to your .nuspec file
    required: false
  csproj:
    description: A path to your csproj file, if the project has any
    required: false
  icon-src:
    description: An external URL for your nuget's icon, if the repo does not already have one
    required: false
  icon-dst:
    description: If you set an external icon source, this should be the full path to the icon, as expected by your nuspec
    required: false
  nuget-key:
    description: Nuget API Key
    required: true
  nuget-feed:
    description: Allows to set a custom Nuget feed. If not set, assumes nuget.org default feed
    required: false
    default: 'https://api.nuget.org/v3/index.json'
  use-symbols:
    description: Allows to explicitely use symbols when packing the nuget.
    required: false
    default: false
  version:
    description: If set, this version will be used when pushing the nuget, overriding nuspec or csproj
    required: false

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: square
  color: gray-dark